package itFest.enums;

public enum ThematicSectionPartner {
    BANNER_AND_OUTDOOR_ADVERTISING_ON_LED_SCREENS,
    SPONSORSHIP_OF_EVENTS_ACTIVITIES_AND_COMPETITIONS_SERVICES,
    MERCHANDISING_AND_PRINTED_MATERIALS,
    BRANDING_OF_ZONES_AND_SITES,
    EXHIBITION_ZONES_AND_DISPLAY_STANDS,
    SPONSORSHIP_INFRASTRUCTURE_AND_LOGISTICS,
    SPEAKER_PARTNERSHIP
}
