version: "3.9"
services:
  backend:
    image: '#image'
    container_name: itfestback
    restart: always
    ports:
      - "80:443"
      - "443:443"
    environment:
      SPRING_PROFILES_ACTIVE: main
      SERVER_PORT: 443
      POSTGRES_DB: jdbc:postgresql://database:5432/postgres
      POSTGRES_USER: itfestuser
      POSTGRES_PASSWORD: itfest2024
      FULLCHAINPEM: /certs/live/itfest.peaksoft.house/fullchain.pem
      PRIVKEYPEM: /certs/live/itfest.peaksoft.house/privkey.pem
    volumes:
      - certs:/certs
  database:
    image: postgres:15
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: itfestuser
      POSTGRES_PASSWORD: itfest2024
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
  certs:
    external: true
